[workspace]
members = [".", "payment-registry"]
resolver = "2"

[package]
name = "payment-contract"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
contract-import = []

[dependencies]
soroban-sdk = "27.0.0"
payment-registry = { path = "payment-registry" }

[dev-dependencies]
soroban-sdk = { version = "27.0.0", features = ["testutils"] }

[profile.release]
overflow-checks = true
